name: CI

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        go-version: ['1.24']

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}

    - name: Build
      run: go build -v ./cmd/imapdu/main.go

    - name: Test
      run: go test -v ./...

    - name: Build for multiple architectures
      if: matrix.os == 'ubuntu-latest'
      run: |
        # Build for common platforms
        GOOS=linux GOARCH=amd64 go build -o builds/imapdu-linux-amd64 ./cmd/imapdu/main.go
        GOOS=linux GOARCH=arm64 go build -o builds/imapdu-linux-arm64 ./cmd/imapdu/main.go
        GOOS=windows GOARCH=amd64 go build -o builds/imapdu-windows-amd64.exe ./cmd/imapdu/main.go
        GOOS=darwin GOARCH=amd64 go build -o builds/imapdu-darwin-amd64 ./cmd/imapdu/main.go
        GOOS=darwin GOARCH=arm64 go build -o builds/imapdu-darwin-arm64 ./cmd/imapdu/main.go

    - name: Create builds directory
      if: matrix.os == 'ubuntu-latest'
      run: mkdir -p builds

    - name: Upload artifacts
      if: matrix.os == 'ubuntu-latest'
      uses: actions/upload-artifact@v4
      with:
        name: binaries
        path: builds/